name: Run Test Suite

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        run: docker build -t app-test .

      - name: Run tests in container
        run: docker run app-test
